name: Deploy to EC2

# Trigger the workflow on push to the 'cicd' branch
on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run a Linux command
        run: ls -la
